# Generated by Django 4.0.4 on 2022-04-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
                ('passed', models.BooleanField(default=False)),
                ('reason', models.CharField(default='', max_length=300)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
