# Generated by Django 4.0.4 on 2022-04-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidadorPautasAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
