# Generated by Django 4.0.4 on 2022-04-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidadorPautasAPI', '0002_alter_documento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
