# Generated by Django 4.0.4 on 2022-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidadorPautasAPI', '0004_remove_documento_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='reason',
            field=models.CharField(default='', max_length=300),
        ),
    ]
