# Generated by Django 4.0.4 on 2022-05-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValidadorPautasAPI', '0005_documento_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='reason',
        ),
    ]
